config/routes.rb
Boxy::Application.routes.draw do
  resources :rooms do
    resources :devices
  end
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  belongs_to :device
end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :details
  accepts_nested_attributes_for :details, :allow_destroy => true

  belongs_to :room

  def groups
    @groups ||= DeviceInformation.groups(self.category)
  end
end

app/models/device_information.rb
DeviceInformation = Object.new

class << DeviceInformation
  Group = Struct.new(:name, :fields)
 
  def categories
    data.keys
  end

  def groups(category)
    data[category].map { |k,v| Group.new(k, v) }
  end
 
  private
 
  def data
    @data ||= YAML.load_file(Rails.root + "config/device_properties.yml")
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :devices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_filter :find_device,     :except => [:new, :create]
  before_filter :decorate_device, :except => [:create, :update, :new]

  def new
    @device = Device.new(:category => params["category"])
    decorate_device
  end

  def create
    device = Device.create(params[:device])
    redirect_to room_device_path(params["room_id"], device.id)
  end

  def update
    @device.update_attributes(params[:device])
    redirect_to room_device_path(params["room_id"], @device.id)
  end

  private

  def find_device
    @device = Device.find(params["id"])
  end

  def decorate_device
    @device = DeviceDecorator.new(@device)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.haml
= form_for(@device, :url => url) do |f|
  = f.hidden_field :category

  = f.label :name
  = f.text_field :name

  - @device.groups.each do |group|
    %h3= group.name

    - group.fields.each do |detail|
      %p
        = f.fields_for :details, detail do |d|
          = d.hidden_field :group
          = d.hidden_field :name

          = d.label :value, "#{detail.name}:"
          = d.text_field :value

  = f.submit

app/views/devices/edit.html.haml
= render :partial => "form", :locals => { :url => room_device_path(@device) } 

app/views/devices/new.html.haml
= render :partial => "form", :locals => { :url => room_devices_path } 

app/views/devices/show.html.haml
%h2= @device.name
%p= link_to "Edit this device", edit_room_device_path(@device)

%ul
  - @device.groups.each do |group|
    %h3= group.name
    - group.fields.each do |detail|
      %p
        = "#{detail.name}: "
        = detail.value

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boxy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>